### Get all contacts
GET https://cse341-gm.onrender.com/contacts

### Get one contact by ID
GET https://cse341-gm.onrender.com/contacts/6824be37bd8b765b934074e8

### POST - Create new contact
POST https://cse341-gm.onrender.com/contacts
Content-Type: application/json

{
  "firstName": "Alice",
  "lastName": "Silva",
  "email": "alice@example.com",
  "favoriteColor": "green",
  "birthday": "1991-05-01"
}

### PUT - Update contact
PUT https://cse341-gm.onrender.com/contacts/682b98e76a83f98d4147db4a
Content-Type: application/json

{
  "firstName": "Alice",
  "lastName": "Silva",
  "email": "alice@example.com",
  "favoriteColor": "yellow",
  "birthday": "1991-05-01"
}

### DELETE - Remove Contact
DELETE https://cse341-gm.onrender.com/contacts/6824d5aabd8b765b934074eb